version: 2.1

jobs:
  docker-tests:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Lanzar contenedor
          command: docker run -e LOG_DIR=$LOG_DIR -e LOG_FILE=$LOG_FILE -t -v `pwd`:/app/test modejota/storagiv

workflows:
  tests:
    jobs:
      - docker-tests