name: Update container and README in Dockerhub

on:
  pull_request:
    branches:
      - main
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.7
      - name: Build container and publish to Docker Hub
        if: |
          contains(steps.changed-files.output.modified-files, 'Dockerfile') ||
          contains(steps.changed-files.output.modified-files, 'package.json') ||
          contains(steps.changed-files.output.modified-files, 'package-lock.json')
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: modejota/storagiv
          tags: latest
      - name: Sync README
        uses: meeDamian/sync-readme@v1.0.6
        with:
        if: |
          contains(steps.changed-files.output.modified-files, 'README.md')
        pass: ${{ secrets.DOCKER_PASS }}
        description: true