name: Update README in Dockerhub

on:
  pull_request:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Sync README
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKER_PASS }}
          description: true